name: Simple CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Generate Prisma client
      run: npx prisma generate

    - name: Run linting
      run: npm run lint

    - name: Run basic validation tests
      run: npm run test:ci

    - name: Build check
      env:
        NEXTAUTH_SECRET: build-secret
        NEXTAUTH_URL: http://localhost:3000
        DATABASE_URL: postgresql://user:pass@localhost:5432/db
        RESEND_API_KEY: re_test_key_for_build
        EMAIL_FROM: test@example.com
        GEMINI_API_KEY: test-key
      run: npm run build

    - name: Success
      run: echo "✅ All quality checks passed! Ready for deployment."

  deployment-ready:
    runs-on: ubuntu-latest
    needs: quality-checks
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deployment Instructions
      run: |
        echo "🎉 All quality checks passed! Your code is ready for deployment."
        echo ""
        echo "To deploy to Vercel:"
        echo "1. Install Vercel CLI: npm i -g vercel"
        echo "2. Login to Vercel: vercel login"
        echo "3. Deploy: vercel --prod"
        echo ""
        echo "Or set up automatic deployment by adding these GitHub secrets:"
        echo "- VERCEL_TOKEN (from https://vercel.com/account/tokens)"
        echo "- VERCEL_ORG_ID (from Vercel project settings)"
        echo "- VERCEL_PROJECT_ID (from Vercel project settings)"